-- Criar tabela quiz_questions
CREATE TABLE quiz_questions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  question_id TEXT UNIQUE NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('objective', 'checkbox', 'matching')),
  difficulty TEXT NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
  category TEXT NOT NULL CHECK (category IN ('introducao', 'aprendizado', 'origens', 'instrumentos')),
  question TEXT NOT NULL,
  options JSONB,
  correct_answers JSONB NOT NULL,
  matching_pairs JSONB,
  explanation TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  created_by UUID REFERENCES auth.users(id),
  last_ai_refinement TIMESTAMPTZ
);

-- Índices
CREATE INDEX idx_quiz_questions_category ON quiz_questions(category);
CREATE INDEX idx_quiz_questions_difficulty ON quiz_questions(difficulty);
CREATE INDEX idx_quiz_questions_active ON quiz_questions(is_active);

-- RLS
ALTER TABLE quiz_questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Quiz questions são públicas para leitura" ON quiz_questions FOR SELECT USING (true);
CREATE POLICY "Admins podem gerenciar quiz questions" ON quiz_questions FOR ALL USING (has_role(auth.uid(), 'admin'));

-- Trigger para updated_at
CREATE TRIGGER update_quiz_questions_updated_at
  BEFORE UPDATE ON quiz_questions
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Migrar perguntas existentes (30 perguntas)
INSERT INTO quiz_questions (question_id, type, difficulty, category, question, options, correct_answers, matching_pairs, explanation) VALUES
('intro-1', 'objective', 'easy', 'introducao', 'O que é uma ''coxilha'' no contexto gaúcho?', '["Uma árvore típica do pampa", "Uma elevação suave e ondulada do pampa", "Um tipo de dança regional", "Um equipamento de montaria"]', '["Uma elevação suave e ondulada do pampa"]', null, 'Coxilha é uma elevação suave e ondulada típica do pampa gaúcho, característica da paisagem sul-rio-grandense.'),
('intro-2', 'matching', 'medium', 'introducao', 'Relacione os termos gaúchos com suas definições:', null, '["Tarumã:Árvore nativa do Sul com sombra generosa", "Querência:Lugar de origem, onde o coração pertence", "Prenda:Mulher gaúcha, companheira", "Galpão:Construção típica da estância, local de convívio"]', '[{"left": "Tarumã", "right": "Árvore nativa do Sul com sombra generosa"}, {"left": "Querência", "right": "Lugar de origem, onde o coração pertence"}, {"left": "Prenda", "right": "Mulher gaúcha, companheira"}, {"left": "Galpão", "right": "Construção típica da estância, local de convívio"}]', 'Esses termos são fundamentais para compreender o universo cultural gaúcho presente na canção.'),
('intro-3', 'checkbox', 'medium', 'introducao', 'Quais desses termos estão relacionados ao chimarrão?', '["Cuia", "Bomba", "Gateado", "Pura-folha", "Coxilha", "Jujado"]', '["Cuia", "Bomba", "Pura-folha", "Jujado"]', null, 'Cuia (recipiente), bomba (canudo de metal), pura-folha (erva de qualidade) e jujado (temperado) são todos relacionados ao ritual do chimarrão.'),
('intro-4', 'objective', 'easy', 'introducao', 'O que significa ''encilhar'' no vocabulário gaúcho?', '["Preparar o chimarrão", "Colocar a sela e arreios no cavalo", "Fechar a porteira da estância", "Acender o fogo no galpão"]', '["Colocar a sela e arreios no cavalo"]', null, 'Encilhar é o ato de preparar o cavalo para montar, colocando a sela (cilha) e os arreios. O oposto é desencilhar.'),
('intro-5', 'objective', 'medium', 'introducao', 'Na canção, o que significa dizer que uma saudade é ''redomona''?', '["Uma saudade tranquila e suave", "Uma saudade rebelde, difícil de domar", "Uma saudade antiga e esquecida", "Uma saudade alegre e festiva"]', '["Uma saudade rebelde, difícil de domar"]', null, 'Redomona se refere a um cavalo ainda não totalmente domado. Por extensão poética, uma ''saudade redomona'' é rebelde, indomável.'),
('intro-6', 'checkbox', 'hard', 'introducao', 'Quais elementos da letra demonstram a relação do gaúcho com a natureza?', '["Sombra do tarumã", "Sol da tarde caindo", "Verso que sonhou ser várzea", "Arreios suados", "Galo para as manhãs", "Esporas em silêncio"]', '["Sombra do tarumã", "Sol da tarde caindo", "Verso que sonhou ser várzea", "Galo para as manhãs"]', null, 'Esses elementos naturais (árvore, sol, planície alagadiça, galo) mostram como a identidade gaúcha está entrelaçada com a paisagem do pampa.'),
('intro-7', 'objective', 'easy', 'introducao', 'O que é uma ''cancela'' no contexto da estância gaúcha?', '["Um tipo de dança", "Uma porteira de madeira", "Um instrumento musical", "Uma peça do arreio do cavalo"]', '["Uma porteira de madeira"]', null, 'Cancela é a porteira típica das estâncias gaúchas, geralmente feita de madeira, que delimita os campos.'),
('intro-8', 'objective', 'medium', 'introducao', 'Por que a canção ''Quando o Verso Vem pras Casa'' foi escolhida para o projeto VersoAustral?', '["Por ser a música gaúcha mais antiga", "Por ter sido a primeira música gaúcha que o pesquisador ouviu", "Por ser a mais tocada no Rio Grande do Sul", "Por ter a letra mais longa"]', '["Por ter sido a primeira música gaúcha que o pesquisador ouviu"]', null, 'A escolha parte de um profundo vínculo afetivo do pesquisador, que teve seu fascínio despertado por essa canção.'),
('apr-1', 'objective', 'easy', 'aprendizado', 'Qual é o compasso característico do chamamé?', '["2/4 (binário)", "3/4 (ternário)", "4/4 (quaternário)", "6/8 (composto)"]', '["3/4 (ternário)"]', null, 'O chamamé é escrito em compasso ternário 3/4, podendo também ser notado em 6/8 (binário composto) para refletir subdivisões rítmicas específicas.'),
('apr-2', 'objective', 'medium', 'aprendizado', 'O que diferencia ritmicamente o chamamé da rancheira?', '["O chamamé tem acentuação no 1° tempo, rancheira no 3°", "O chamamé tem acentuação no 3° tempo, rancheira no 1°", "Ambos têm a mesma acentuação", "O chamamé não tem acentuação definida"]', '["O chamamé tem acentuação no 3° tempo, rancheira no 1°"]', null, 'A ''puxada'' de fole do acordeão no chamamé cria acentuação no 3° tempo do compasso, enquanto a rancheira acentua o 1° tempo.'),
('apr-3', 'checkbox', 'easy', 'aprendizado', 'Quais instrumentos formam a base típica do chamamé?', '["Acordeão", "Violão", "Bombo leguero", "Piano", "Violino", "Bateria"]', '["Acordeão", "Violão", "Bombo leguero"]', null, 'O acordeón (trazido pelos italianos), o violão e o bombo leguero (percussão argentina) são os instrumentos base do chamamé.'),
('apr-4', 'matching', 'medium', 'aprendizado', 'Relacione cada etnia com sua contribuição para a música gaúcha:', null, '["Italianos:Introdução do acordeão", "Espanhóis:Violão e bombo leguero", "Portugueses:Primeiros colonizadores", "Rio da Prata:Influência cultural platina"]', '[{"left": "Italianos", "right": "Introdução do acordeão"}, {"left": "Espanhóis", "right": "Violão e bombo leguero"}, {"left": "Portugueses", "right": "Primeiros colonizadores"}, {"left": "Rio da Prata", "right": "Influência cultural platina"}]', 'Cada grupo étnico contribuiu com elementos específicos para formar a rica diversidade musical gaúcha.'),
('apr-5', 'checkbox', 'medium', 'aprendizado', 'Quais são características gerais dos gêneros musicais gaúchos?', '["Preferência pelo modo Maior", "Tonalidades com sustenidos (especialmente Mi Maior)", "Uso exclusivo de modo Menor", "Melodia simples por graus conjuntos", "Harmonia complexa com sétimas e nonas", "Compassos binários e ternários"]', '["Preferência pelo modo Maior", "Tonalidades com sustenidos (especialmente Mi Maior)", "Melodia simples por graus conjuntos", "Compassos binários e ternários"]', null, 'A música gaúcha caracteriza-se pela simplicidade melódica, preferência por tonalidades maiores com sustenidos, e compassos simples.'),
('apr-6', 'objective', 'hard', 'aprendizado', 'Por que o chamamé pode ser notado tanto em 3/4 quanto em 6/8?', '["São notações completamente equivalentes sem diferença", "3/4 é usado para iniciantes, 6/8 para profissionais", "6/8 reflete subdivisões guaranis, 3/4 é mais moderno", "Apenas 3/4 é correto, 6/8 é um erro"]', '["6/8 reflete subdivisões guaranis, 3/4 é mais moderno"]', null, 'A notação em 6/8 reflete subdivisões rítmicas herdadas das tradições guaranis, enquanto 3/4 é mais comum em partituras modernas, mas ambas preservam a acentuação característica.'),
('apr-7', 'checkbox', 'easy', 'aprendizado', 'Quais danças fazem parte do fandango gaúcho?', '["Vaneira", "Chamamé", "Samba", "Milonga", "Forró", "Rancheira"]', '["Vaneira", "Chamamé", "Milonga", "Rancheira"]', null, 'Vaneira, chamamé, milonga e rancheira são algumas das danças de fandango tradicionais do Rio Grande do Sul.'),
('apr-8', 'objective', 'medium', 'aprendizado', 'Qual a função harmônica predominante na música gaúcha?', '["Tônica, dominante e subdominante", "Apenas tônica e dominante", "Acordes dissonantes modernos", "Sem harmonia definida"]', '["Tônica, dominante e subdominante"]', null, 'A harmonia na música gaúcha é tradicionalmente simples, baseada nas três funções harmônicas principais: tônica, dominante e subdominante.'),
('ori-1', 'objective', 'easy', 'origens', 'De onde vem a palavra ''chamamé''?', '["Do espanhol ''chamar''", "Do guarani ''che amó memé'' (eu también soy, yo soy de aquí)", "Do português ''chamariz''", "Do italiano ''chiamare''"]', '["Do guarani ''che amó memé'' (eu también soy, yo soy de aquí)"]', null, 'A etimologia guarani ''che amó memé'' revela a essência identitária do chamamé: uma música que diz ''eu também sou, eu sou daqui''.'),
('ori-2', 'checkbox', 'medium', 'origens', 'Quais elementos culturais indígenas estão presentes no chamamé?', '["Língua guarani em expressões", "Instrumentos de percussão tradicionais", "Escalas pentatônicas", "Rituais xamânicos", "Narrativas orais", "Cosmologia ameríndia"]', '["Língua guarani em expressões", "Instrumentos de percussão tradicionais", "Narrativas orais"]', null, 'O chamamé preserva a língua guarani, instrumentos percussivos tradicionais e a tradição oral narrativa dos povos originários.'),
('ori-3', 'matching', 'medium', 'origens', 'Relacione os países platinos com suas características culturais:', null, '["Argentina:Berço principal do chamamé", "Uruguai:Influência cultural compartilhada", "Paraguai:Raízes guaranis fortes", "Brasil (RS):Absorção e adaptação regional"]', '[{"left": "Argentina", "right": "Berço principal do chamamé"}, {"left": "Uruguai", "right": "Influência cultural compartilhada"}, {"left": "Paraguai", "right": "Raízes guaranis fortes"}, {"left": "Brasil (RS)", "right": "Absorção e adaptação regional"}]', 'A região platina compartilha uma identidade cultural que atravessa fronteiras políticas, com cada país contribuindo para o chamamé.'),
('ori-4', 'objective', 'medium', 'origens', 'Qual o papel das reduções jesuíticas na formação do chamamé?', '["Proibiram a música guarani completamente", "Criaram síntese entre música sacra europeia e tradições guaranis", "Não tiveram influência na música regional", "Apenas ensinaram música europeia aos indígenas"]', '["Criaram síntese entre música sacra europeia e tradições guaranis"]', null, 'As reduções jesuíticas foram espaços de encontro cultural onde a música sacra europeia se mesclou com as tradições musicais guaranis.'),
('ori-5', 'objective', 'hard', 'origens', 'O que o Rio da Prata representa geograficamente?', '["Um rio que nasce no Rio Grande do Sul", "Um estuário formado pelos rios Paraná e Uruguai", "Uma baía no litoral argentino", "Um lago compartilhado entre países platinos"]', '["Um estuário formado pelos rios Paraná e Uruguai"]', null, 'O Rio da Prata é um estuário (encontro de rios com o oceano) formado pelos rios Paraná e Uruguai, localizado entre Uruguai e Argentina.'),
('ori-6', 'checkbox', 'easy', 'origens', 'Quais povos contribuíram para a música sul-rio-grandense?', '["Portugueses", "Alemães", "Italianos", "Japoneses", "Ingleses", "Africanos"]', '["Portugueses", "Alemães", "Italianos", "Japoneses", "Africanos"]', null, 'Portugueses, alemães, italianos, japoneses, africanos, indígenas, espanhóis, poloneses e franceses contribuíram para a diversidade musical gaúcha.'),
('ori-7', 'objective', 'medium', 'origens', 'Quando os imigrantes espanhóis chegaram ao Brasil trazendo instrumentos musicais?', '["Século XVII", "Final do século XIX e início do XX", "Metade do século XVIII", "Após a Segunda Guerra Mundial"]', '["Final do século XIX e início do XX"]', null, 'Os espanhóis chegaram ao Brasil principalmente no final do século XIX e início do século XX, trazendo violão e bombo leguero.'),
('ori-8', 'checkbox', 'hard', 'origens', 'Quais características do chamamé refletem a herança guarani?', '["Uso de instrumentos de percussão tradicionais", "Subdivisões rítmicas específicas (notadas em 6/8)", "Acordeão como instrumento principal", "Expressões linguísticas guaranis", "Compasso binário 2/4", "Narrativas e cosmologia nas letras"]', '["Uso de instrumentos de percussão tradicionais", "Subdivisões rítmicas específicas (notadas em 6/8)", "Expressões linguísticas guaranis", "Narrativas e cosmologia nas letras"]', null, 'A herança guarani manifesta-se em múltiplas camadas: instrumentos, ritmo, língua e cosmovisão narrativa.'),
('inst-1', 'objective', 'easy', 'instrumentos', 'Qual é o instrumento predecessor do violão no chamamé, de origem guarani?', '["Bandoneón", "Mbaracá", "Charango", "Cuatro"]', '["Mbaracá"]', null, 'O Mbaracá era um instrumento de cordas guarani pré-hispânico, feito de cabaça, que antecedeu o violão na região.'),
('inst-2', 'objective', 'medium', 'instrumentos', 'O que é o ''Toque de Tupã'' no contexto do chamamé?', '["Uma dança tradicional", "Uma técnica ritual de tocar violão para concentração e transe", "Um tipo de acordeão especial", "Um gênero musical derivado do chamamé"]', '["Uma técnica ritual de tocar violão para concentração e transe"]', null, 'O ''Toque de Tupã'' é uma técnica sagrada de execução do violão no chamamé, usada para concentração e transe espiritual.'),
('inst-3', 'objective', 'medium', 'instrumentos', 'O que é o ''rasguear chamamecero'' no violão?', '["Uma afinação especial das cordas", "Uma técnica de dedilhado suave", "Um rasgueado percussivo que divide bordões e primas", "Um tipo de harmônico artificial"]', '["Um rasgueado percussivo que divide bordões e primas"]', null, 'O rasguear chamamecero é uma técnica percussiva desenvolvida por Nicolas Antonio Niz, que cria efeito rítmico dividindo bordões e primas.'),
('inst-4', 'checkbox', 'easy', 'instrumentos', 'Quais características definem o acordeão no contexto gaúcho?', '["Trazido por imigrantes italianos", "Chamado de ''gaita''", "Instrumento central do chamamé", "Usado apenas em músicas religiosas", "Substituiu completamente o violão", "Fundamental para o timbre da música gaúcha"]', '["Trazido por imigrantes italianos", "Chamado de ''gaita''", "Instrumento central do chamamé", "Fundamental para o timbre da música gaúcha"]', null, 'O acordeão (gaita) foi trazido por italianos e tornou-se o instrumento central do chamamé, definindo o timbre da música gaúcha.'),
('inst-5', 'objective', 'hard', 'instrumentos', 'Qual a relação entre o violão no chamamé e a tonalidade de Fá?', '["É a única tonalidade permitida", "É a tonalidade mais comum devido ao Toque de Tupã", "Não há relação específica", "Fá é proibido no chamamé tradicional"]', '["É a tonalidade mais comum devido ao Toque de Tupã"]', null, 'O Toque de Tupã tradicionalmente usa a tonalidade de Fá, tornando-a comum no chamamé executado ao violão.'),
('inst-6', 'objective', 'medium', 'instrumentos', 'Quem foi Nicolas Antonio Niz?', '["Um luthier italiano", "Pioneiro do rasguear chamamecero no violão", "Inventor do acordeão", "Compositor do primeiro chamamé"]', '["Pioneiro do rasguear chamamecero no violão"]', null, 'Nicolas Antonio Niz foi pioneiro em desenvolver a técnica de rasguear chamamecero, revolucionando a execução do violão no gênero.');